use_frameworks!

platform :ios, '9.0'

target 'WXNSDK7_Example' do
  pod 'WXNSDK7', :path => '../'

  target 'WXNSDK7_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
